version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      workflows:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "conda"
    directories:
      - "tests/**/*"
    schedule:
      interval: "daily"
    groups:
      test_environments:
        group-by: "dependency-name"

