name: build-book

on:
  workflow_call:
    inputs:
      environment_name:
        description: "Name of conda environment to activate (NO LONGER USED)"
        required: false
        default: "cookbook-dev"
        type: string
      environment_file:
        description: "Name of conda environment file"
        required: false
        default: "environment.yml"
        type: string
      path_to_notebooks:
        description: "Location of the JupyterBook source relative to repo root"
        required: false
        default: "."
        type: string
      artifact_name:
        description: "The name to assign to the built book artifact."
        required: false
        default: "book-zip"
        type: string
      build_command:
        description: "The linux command to build the book or site."
        required: false
        default: "myst build --execute --html"
        type: string
      output_path:
        description:
          "Path to the built html content relative to `path_to_notebooks`"
        required: false
        default: "_build/html"
        type: string
      build_from_code_artifact:
        description:
          "Should we try to build from a previously uploaded code artifact?"
        required: false
        default: "false"
        type: string
      code_artifact_name:
        description:
          "Name of zipped artifact passed in, instead of checking out the
          repository."
        required: false
        default: "code-zip"
        type: string
      base_url:
        description:
          "Determines where the website is served from, including CSS & JS
          assets (needed for MyST)"
        required: false
        default: "/${{ github.event.repository.name }}"
        type: string

    secrets:
      PRIVATE_KEY:
        description:
          "Google analytics key needed for metrics page on portal site"
        required: false
      PRIVATE_KEY_ID:
        description:
          "Google analytics key id needed for metrics page on portal site"
        required: false
      ARM_USERNAME:
        description:
          "Username for the ARM Data Discovery portal
          (https://adc.arm.gov/armlive/)"
        required: false
      ARM_PASSWORD:
        description:
          "Password for the ARM Data Discovery portal
          (https://adc.arm.gov/armlive/)"
        required: false
      AQS_USERNAME:
        description: "Username for the AQS Data Portal"
        required: false
      AQS_KEY:
        description: "Key for the AQS Data Portal"
        required: false
      EARTHDATA_USERNAME:
        description: "NASA Earthdata API Username"
        required: false
      EARTHDATA_PASSWORD:
        description: "NASA Earthdata API Password"
        required: false

env:
  # the BASE_URL environment variable needs to be set if building with myst
  BASE_URL: ${{ inputs.base_url }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout the code from the repo
        if: inputs.build_from_code_artifact == 'false'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      #  The next two steps should replicated checking out the code
      - name: Download code artifact
        id: get_code_artifact
        if: inputs.build_from_code_artifact == 'true'
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: ${{ inputs.code_artifact_name }}

      - name: Setup environment with micromamba
        uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-file: ${{ inputs.environment_file }}

      - name: Build the book
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          ARM_USERNAME: ${{ secrets.ARM_USERNAME }}
          ARM_PASSWORD: ${{ secrets.ARM_PASSWORD }}
          AQS_USERNAME: ${{ secrets.AQS_USERNAME }}
          AQS_KEY: ${{ secrets.AQS_KEY }}
          EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
          EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
          SECRETS_VARS: ${{ toJson(secrets) }}
        run: |
          cd ${{ inputs.path_to_notebooks }}
          ${{ inputs.build_command }}

      - name: Upload zipped book artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.path_to_notebooks}}/${{ inputs.output_path}}

