name: ci

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "tests/**"
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/**"
      - "tests/**"
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: $${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-checks:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run actionlint with annotations
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color

  build-book:
    strategy:
      fail-fast: false
      matrix:
        cookbook:
          - default
    uses: ./.github/workflows/build-book.yaml
    with:
      path_to_notebooks: tests/${{ matrix.cookbook }}
      environment_file: tests/${{ matrix.cookbook }}/environment.yml
      artifact_name: ${{ matrix.cookbook }}-book-zip
      base_url: /${{ github.event.repository.name }}/tests/${{ matrix.cookbook }}
    secrets: inherit

  link-checker:
    strategy:
      fail-fast: false
      matrix:
        cookbook:
          - default
    uses: ./.github/workflows/link-checker.yaml
    with:
      path_to_notebooks: tests/${{ matrix.cookbook }}
      environment_file: tests/${{ matrix.cookbook }}/environment.yml

