name: deploy-book

on:
  workflow_call:
    inputs:
      artifact_name:
        description:
          "Name of the artifact (zipped book) created by previous build step"
        required: false
        default: book-zip
        type: string
      destination_dir:
        description:
          "Path to publish to on GitHub Pages, relative to site root. We use
          this to deploy previews in a subdirectory."
        required: false
        default: ""
        type: string
      publish_dir:
        description: "Publish dir for the action"
        required: false
        default: "_build/html"
        type: string
      dry_run:
        description: "Toggle read-only reporting for testing"
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-slim
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Download merged artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ inputs.artifact_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          path: ${{ inputs.publish_dir }}

      - name: Test and report
        run: |
          echo "Would push contents of ${{ inputs.publish_dir }}"
          echo "to gh-pages:${{ inputs.destination_dir }}"
          echo "---"
          echo "Contents from ${{ inputs.artifact_name }}:"
          [[ $(ls -A ${{ inputs.publish_dir }}) ]] && echo "found." || echo "::error ::No artifact files found"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        if: github.ref == 'refs/heads/main' && inputs.dry_run == false
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          git-config-name: 'github-actions[bot]'
          git-config-email: 'github-actions[bot]@users.noreply.github.com'
          branch: gh-pages
          folder: ${{ inputs.publish_dir }}
          clean: true
          clean-exclude: _preview/* # keep existing previews from other PRs
          target-folder: ${{ inputs.destination_dir }}
